<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>
    </RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>XLExportExamples</AssemblyTitle>
    <Product>XLExportExamples</Product>
    <Copyright>Copyright ©  2015</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DefineDebug>false</DefineDebug>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.RichEdit.Export" Version="24.2.*-*" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
</Project>